### ISSUE TITLE
error: redefinition of ‘struct at::_ops::lu_solve’

### ISSUE THREAD

**Issue by HuangDou228** [dstx123/unitree_rl#1]
`/home/huangdou/libtorch/include/ATen/Operators.h:16182:18: error: redefinition of ‘struct at::_ops::lu_solve’
16182 | struct TORCH_API lu_solve {
      |                  ^~~~~~~~
/home/huangdou/unitree/unitree_rl_cpp/src/unitree_guide/unitree_guide/include/thirdParty/quadProgpp/Array.hh:2169:15: note: previous definition of ‘struct at::_ops::lu_solve’
 2169 | #define solve lu_solve
      |               ^~~~~~~~
`
I believe this error is due to a duplicate definition of **lu_solve** in the file include/thirdParty/quadProgpp/Array.hh

**Comment by dstx123** [comment]
Yes, just replace lu_solve in libtorch with another name. This function has been defined in unitree_guide.

**Comment by HuangDou228** [comment]
> Yes, just replace lu_solve in libtorch with another name. This function has been defined in unitree_guide.

Instead of replace lu_solve in libtorch, I choose to replace lu_solve in Array.hh.
All I did was simply replace **#define solve lu_solve** with **#define solve lu_solves** and the problem was solved after that.
