### ISSUE TITLE
Porting to Jetson

### ISSUE THREAD

**Issue by hanzhi0410** [dstx123/unitree_rl#2]
Thank you for your work. Do you have the aarch64 version of libtorch. so? I encountered an error file in wrong format when porting to Jetson,

**Comment by dstx123** [comment]
Sorry, this repository is not adapted for Jetson devices yet. You can try to find a suitable version of libtorch adapted for Jetson to compile, or using tensorRT is also a good choice.
The version adapted to Jetson will be updated in the future. Currently, you can try to deploy it through a network cable. 
By the way, if you successfully deploy your code on Jetson, you are welcome to provide detailed implementation details.

**Comment by hanzhi0410** [comment]
Install arm64 version of pytorch on Jetson without changing this repository, where the required libtorch exists,
Change torch path:
If (useTotarch)
Set (Torch-DIR/youth/library/share/make/Torch) # Set library path
Find_package (Torch Required)
Just go to the corresponding position,
Please also note that in/home/hn/legged_RL/unitree_rl master/src/unitree_ros master/unitree_legged_control/CMakeLists.txt, targetunlink-libraries (unitree_legged_control ${catkin-LIBRARIES} unitree_jointControl_tool) should be changed to targetunlink-libraries (unitree_legged_control ${catkin-LIBRARIES} unitree_jointControl_tool-arm64)

**Comment by dstx123** [comment]
> Install arm64 version of pytorch on Jetson without changing this repository, where the required libtorch exists, Change torch path: If (useTotarch) Set (Torch-DIR/youth/library/share/make/Torch) # Set library path Find_package (Torch Required) Just go to the corresponding position, Please also note that in/home/hn/legged_RL/unitree_rl master/src/unitree_ros master/unitree_legged_control/CMakeLists.txt, targetunlink-libraries (unitree_legged_control ${catkin-LIBRARIES} unitree_jointControl_tool) should be changed to targetunlink-libraries (unitree_legged_control ${catkin-LIBRARIES} unitree_jointControl_tool-arm64)

I'm glad to hear your success.
