### ISSUE TITLE
How to get Adapt_model and Body_model?

### ISSUE THREAD

**Issue by HuangDou228** [dstx123/unitree_rl#3]
`   torch::jit::script::Module _body_module;
    torch::jit::script::Module _adapt_module;
    torch::jit::script::Module _privileged_module;
    torch::jit::script::Module _scandots_module;
`

`void State_RL::_action_compute()
{
    torch::Tensor latent = _adapt_module.forward({this->_obs_buffer_tensor}).toTensor();
    this->_action = _body_module.forward({torch::cat({_observation, latent}, -1)}).toTensor();
    this->_action = torch::clamp(this->_action, -clip_actions, clip_actions);
    .......
}`

I know that the adapt_model provides a latent tensor, and that this latent tensorcan be used to get the joint angles through the body_model with the observation tensor . But what is this latent tensor? How do I get the adapt_model with the body_model?

I learned that I can get a go2 robot through Isaacgym, Is this a body_model?

By the way, what is the _privileged_module and _scandots_module in this code? They don't seem to be used in this project.

**Comment by dstx123** [comment]
"_privileged_module" and "_scandots_module" is the testing code for my own model, which you could feel relax to delete. 
“adapt_model” and “body_model” are only provided as an example. You can freely replace them according to your training model. You only need to pay attention to the matching of input and output. 
This repository only provides an example, which is highly extensible. Here is a demonstration video: https://www.bilibili.com/video/BV1Gt421M7NV/?spm_id_from=333.999.0.0&vd_source=5f2437f40dc85b8d866187b401f714d2
